// src/lib/components/Footer.svelte
<script lang="ts">
	//TODO update these links, and move them to a icon library
	const socialLinks = [
		{ href: 'https://www.facebook.com/', label: 'Facebook', src: '/Images/FaceBookNew.png' },
		{ href: 'https://www.instagram.com/', label: 'Instagram', src: '/Images/InstagramNew.png' },
		{ href: 'https://x.com/', label: 'Twitter', src: '/Images/TwitterNew.png' },
		{
			href: 'https://github.com/sorrymint/ihcc-csd',
			label: 'GitHub',
			src: '/Images/gitHubLogo.png'
		},
		{ href: 'https://www.linkedin.com/', label: 'LinkedIn', src: '/Images/LinkedInNew.png' }
	];
</script>

<footer class="site-footer">
	<div class="footer-shell">
		<h2 class="font-matrixtype">Interested In Joining?</h2>

		<p class="footer-copy desktop-copy">
			Everyone is welcome to join, <a href="/events">Click Here</a>to view upcoming events
		</p>

		<div class="cta-row">
			<a class="cta-link" href="/contact">Join Now</a>
		</div>

		<div class="footer-grid">
			<a class="shrink-0" href="/" aria-label="Go to home page">
				<img
					src="/Images/Code.svg"
					alt="Computer Software Development Club Logo"
					class="h-20 w-auto md:h-12"
				/>
			</a>

			<div class="social-links">
				{#each socialLinks as link (link.href)}
					<a href={link.href} target="_blank" rel="noreferrer" aria-label={link.label}>
						<img src={link.src} alt={link.label} width="28" height="28" />
					</a>
				{/each}
			</div>
		</div>
	</div>
</footer>

<!-- TODO change to tailwind -->
<style>
	.site-footer {
		margin-top: 4rem;
	}

	.footer-shell {
		background: #e5e5e5;
		padding: 2rem 1rem;
	}

	h2 {
		margin: 0;
		text-align: center;
		font-size: clamp(2rem, 4vw, 2.5rem);
		font-weight: 700;
		color: #701730;
	}

	.footer-copy {
		margin: 1.25rem auto 0;
		max-width: 34rem;
		text-align: center;
		font-size: 0.95rem;
		color: #262626;
	}

	.footer-copy a {
		margin: 0 0.35rem;
		color: #f77c00;
	}

	.cta-row {
		display: flex;
		justify-content: center;
		margin-top: 1.5rem;
	}

	.cta-link {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		padding: 0.8rem 1.5rem;
		border-radius: 999px;
		background: #ffa400;
		color: #262626;
		text-decoration: none;
		font-size: 0.875rem;
		font-weight: 700;
		letter-spacing: 0.08em;
		text-transform: uppercase;
	}

	.footer-grid {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 1.5rem;
		margin-top: 2rem;
	}

	.footer-logo img {
		display: block;
	}

	.quick-links {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 0.75rem;
	}

	.quick-links a {
		color: #000;
		text-decoration: none;
		font-weight: 700;
		text-transform: uppercase;
	}

	.social-links {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 1rem;
		flex-wrap: wrap;
	}

	.social-links img {
		display: block;
	}

	.desktop-copy {
		display: none;
	}

	@media (min-width: 768px) {
		.footer-shell {
			padding: 2rem 1.5rem;
		}

		.footer-grid {
			flex-direction: row;
			justify-content: space-evenly;
		}

		.quick-links {
			flex-direction: row;
			gap: 2rem;
		}

		.desktop-copy {
			display: block;
		}

		.mobile-copy {
			display: none;
		}
	}
</style>

// src/app/Components/Footer.tsx
import Image from "next/image";
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="">
      <div className=" bg-[#E5E5E5] py-8  space-y-10">
        <h2 className="font-bold flex items-center justify-center text-center text-4xl text-[#701730]">
          Interested In Joining?
        </h2>

        <p className="hidden md:block text-sm text-center text-gray-800 mt-5">
          Everyone is welcome to join,{" "}
          <Link
            className="underline text-sm text-[#F77C00]/90"
            href="/Events"
          >
            Click Here
          </Link>{" "}
          to view upcoming events.
        </p>

        <div className="flex items-center justify-center mt-5">
          <br></br>
          <button
            className="rounded-full p-3 pr-6 pl-6 bg-[#FFA400] text-sm text-gray-800 font-bold shadow-lg cursor-pointer tracking-[1.5px] uppercase transition-all duration-150 ease-linear hover:tracking-[3px] hover:bg-[#F77C00] hover:shadow-[0_7px_29px_0px_#F77C00] active:tracking-[3px] active:bg-[#F77C00] active:shadow-[0_0px_0px_0px_#F77C00] active:translate-y-[5px] active:duration-100"
            title="Join"
          >
            <Link href="/Contact">Join Here</Link>
          </button>
        </div>

        <div className="md:flex md:items-center md:justify-evenly">
          <div className="hidden md:block">
            <Link href="/">
              <Image
                className=""
                src="/images/CSDClubLogo-removebg-preview.svg"
                alt="Computer Software Development Club Logo"
                width={95}
                height={25}
                title="Home"
              />
            </Link>
          </div>

          <div className="flex flex-col md:flex-row md:max-sm:inline-block md:max-sm:pl-15 md:pl-20 my-8">
            <hr className="w-11/12 ml-4 md:hidden" />
            <Link href="/Our-Mission">
              <p className="font-bold text-[000000] m-3 ml-4">OUR MISSION</p>
            </Link>
            <hr className="w-11/12 ml-4 md:hidden" />
            <Link
              href="/Contact"
              className="md:pr-9 md:pl-9 font-bold text-[000000] m-3 ml-4"
            >
              CONTACT US
            </Link>
            <hr className="w-11/12 ml-4 md:hidden" />
            <Link href="/AboutCSD">
              <p className="font-bold text-[000000] m-3 ml-4">ABOUT CSD</p>
            </Link>
            <hr className="w-11/12 ml-4 md:hidden" />
          </div>

          <div className="flex flex-row justify-evenly mb-15 md:mb-0 items-center">
            <Link href="https://www.facebook.com/" target="_blank">
              <Image
                className="h-7 mx-2"
                src="/images/FaceBookNew.png"
                alt="FaceBook"
                width={28}
                height={7}
                title="Facebook"
              />
            </Link>
            <Link href="https://www.instagram.com/" target="_blank">
              <Image
                className="h-7 mx-2"
                src="/images/InstagramNew.png"
                alt="Instagram"
                width={28}
                height={7}
                title="Instagram"
              />
            </Link>
            <Link href="https://x.com/" target="_blank">
              <Image
                className="h-7 mx-2"
                src="/images/TwitterNew.png"
                alt="Twitter"
                width={28}
                height={7}
                title="Twitter"
              />
            </Link>
            <Link href="https://github.com/sorrymint/ihcc-csd" target="_blank">
              <Image
                className="h-7 mx-2"
                src="/images/gitHubLogo.png"
                alt="GitHub"
                width={28}
                height={7}
                title="Github"
              />
            </Link>
            <Link href="https://www.linkedin.com/" target="_blank">
              <Image
                className="h-7 mx-2"
                src="/images/LinkedInNew.png"
                alt="LinkedIn"
                width={28}
                height={7}
                title="LinkedIn"
              />
            </Link>
          </div>

          <p className="text-sm text-center text-gray-800 px-5 pb-5 md:hidden">
            Everyone is welcome to join,{" "}
            <span
            title="View Events">
              <Link
                className="underline text-sm text-[#F77C00]/90"
                href="/Events"
                title="View Events"
              >
                Click Here
              </Link>
            </span>{" "}
            to view upcoming events.
          </p>
        </div>
      </div>
    </footer>
  );
}
