// src/lib/components/Header.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { primaryPages } from '$lib/site-navigation';

	let menuOpen = $state(false);
	let isVisible = $state(true);

	const isActive = (href: string) =>
		href === '/'
			? page.url.pathname === '/'
			: page.url.pathname === href || page.url.pathname.startsWith(`${href}/`);

	onMount(() => {
		let lastScrollY = window.scrollY;

		const controlHeader = () => {
			const currentScrollY = window.scrollY;
			isVisible = currentScrollY <= lastScrollY || currentScrollY <= 20;
			lastScrollY = currentScrollY;
		};

		window.addEventListener('scroll', controlHeader, { passive: true });

		return () => window.removeEventListener('scroll', controlHeader);
	});
</script>

<nav class:nav-hidden={!isVisible} class="site-header">
	<div class="header-shell">
		<div class="brand-row">
			<div class="brand-group">
				<button
					type="button"
					class="menu-toggle"
					onclick={() => (menuOpen = !menuOpen)}
					aria-expanded={menuOpen}
					aria-controls="mobile-navigation"
					aria-label={menuOpen ? 'Close menu' : 'Open menu'}
				>
					<span aria-hidden="true">{menuOpen ? '✕' : '☰'}</span>
				</button>

				<a class="brand-link" href="/" aria-label="Go to home page">
					<img
						src="/Images/CSDClubLogo-removebg-preview.svg"
						alt="Computer Software Development Club Logo"
						width="40"
						height="40"
					/>
				</a>
			</div>

			<div class="desktop-links">
				{#each primaryPages as link (link.href)}
					<a href={link.href} class:active-link={isActive(link.href)}>{link.label}</a>
				{/each}
			</div>
		</div>
	</div>

	<div id="mobile-navigation" class:mobile-open={menuOpen} class="mobile-panel">
		<div class="mobile-links">
			{#each primaryPages as link (link.href)}
				<a
					href={link.href}
					class:active-mobile-link={isActive(link.href)}
					onclick={() => (menuOpen = false)}
				>
					{link.label}
				</a>
			{/each}
		</div>
	</div>
</nav>

<style>
	.site-header {
		position: fixed;
		top: 0;
		left: 0;
		z-index: 50;
		width: 100%;
		transition: transform 0.3s ease;
	}

	.nav-hidden {
		transform: translateY(-100%);
	}

	.header-shell {
		margin: 0.75rem;
		border-radius: 1rem;
		background: #e5e5e5;
		box-shadow: 0 10px 24px rgba(0, 0, 0, 0.08);
	}

	.brand-row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 1rem;
		min-height: 4.5rem;
		padding: 0 1rem;
	}

	.brand-group {
		display: flex;
		align-items: center;
		gap: 0.75rem;
	}

	.brand-link {
		display: inline-flex;
		align-items: center;
	}

	.brand-link img {
		display: block;
	}

	.menu-toggle {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 2.5rem;
		height: 2.5rem;
		border: 0;
		border-radius: 0.75rem;
		background: transparent;
		color: #0d0d0d;
		font-size: 1.5rem;
		cursor: pointer;
	}

	.menu-toggle:hover {
		background: rgba(0, 0, 0, 0.06);
	}

	.desktop-links {
		display: none;
		align-items: center;
		gap: 1.5rem;
	}

	.desktop-links a,
	.mobile-links a {
		color: #262626;
		text-decoration: none;
		font-weight: 600;
		transition:
			color 0.2s ease,
			background-color 0.2s ease;
	}

	.active-link {
		color: #f77c00;
		border-bottom: 2px solid #f77c00;
		padding-bottom: 0.25rem;
	}

	.mobile-panel {
		max-height: 0;
		overflow: hidden;
		opacity: 0;
		transition:
			max-height 0.3s ease,
			opacity 0.3s ease;
	}

	.mobile-open {
		max-height: 24rem;
		opacity: 1;
	}

	.mobile-links {
		margin: 0 0.75rem;
		margin-top: -0.25rem;
		padding: 2rem 0.75rem 0.75rem;
		border-radius: 0 0 1rem 1rem;
		background: #e5e5e5;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.mobile-links a {
		padding: 0.85rem 0.75rem;
		border-radius: 0.75rem;
	}

	.mobile-links a:hover {
		background: rgba(0, 0, 0, 0.06);
	}

	.active-mobile-link {
		background: #dfdcdc;
		color: #f77c00;
	}

	@media (min-width: 768px) {
		.brand-row {
			padding: 0 1.5rem;
		}

		.menu-toggle,
		.mobile-panel {
			display: none;
		}

		.desktop-links {
			display: flex;
		}
	}
</style>

// src/app/Components/Header.tsx
"use client";
import Link from "next/link";
import { useState, useEffect } from "react";
import { usePathname } from "next/navigation";
import { Menu, X } from "lucide-react";
import Image from "next/image";

export default function Header() {
  // For moblie
  const [menuOpen, setMenuOpen] = useState(false);
  // For on Scoll
  const [isVisible, setVisible] = useState(true);
  // Directing to the certain pages
  const pathname = usePathname();

  // PURPOSE: check if the user has scroll, depeding of the result it will hid the navbar or diplay it when scolled up.
  useEffect(() => {
    let lastScrollY = window.scrollY;
    const controlHeader = () => {
      const currentScrollY = window.scrollY;

      if (currentScrollY > lastScrollY && currentScrollY > 20) {
        setVisible(false);
      } else {
        setVisible(true);
      }

      lastScrollY = currentScrollY;
    };

    window.addEventListener("scroll", controlHeader);

    return () => window.removeEventListener("scroll", controlHeader);
  }, []);

  const headerLinks = [
    { href: "/", label: "Home" },
    { href: "/Blog", label: "Blog" },
    { href: "/Notes", label: "Notes" },
    { href: "/Events", label: "Events" },
    { href: "/Contact", label: "Contact" },
    { href: "/Alumni", label: "Alumni" },
    { href: "/Podcast", label: "Podcast" },
  ];

  return (
    <nav
      className={`fixed w-full transition-transform duration-300 z-50 ${
        isVisible ? "transition-y-0" : "-translate-y-full"
      }  `}
    >
      <div
        className={`px-4 sm:px-6 md:px-14 lg:px-18 bg-[#E5E5E5] rounded-2xl mx-3 mt-3 h-18 shadow-md`}
      >
        <div className="flex h-full w-full items-center">
          <div className="flex gap-2 items-center w-full justify-between ">
            <div className="flex items-center gap-4">
              <button
                onClick={() => setMenuOpen(!menuOpen)}
                className=" md:hidden inline-flex items-center justify-center p-2 rounded-md text-gray-600 hover:text-gray-900 hover:bg-gray-100 focus:outline-none "
                title="Menu"
              >
                {!menuOpen ? (
                  <Menu
                    className="text-3xl"
                    strokeWidth={3}
                    color={"#0D0D0D"}
                  />
                ) : (
                  <X className="text-3xl " strokeWidth={3} color={"#0D0D0D"} />
                )}
              </button>
              <div className="flex items-center ">
                <Link href="/">
                  <Image
                    className=""
                    src="/Images/CSDClubLogo-removebg-preview.svg"
                    alt="Computer Software Development Club Logo"
                    width={40}
                    height={40}
                    title="Home Button"
                  />
                </Link>
              </div>
            </div>

            <div className="hidden md:flex items-center space-x-2 lg:space-x-6">
              {headerLinks.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className={`text-gray-800 hover:text-neutral-800 px-2 py-2 text-md font-semibold transition-colors ${
                    pathname === link.href ? "border-b-2 text-[#FFA400]!" : ""
                  }`}
                  title={`${link.label}`}
                >
                  {link.label}
                </Link>
              ))}
            </div>
            <div className=" w-24">
              <button
                className={`rounded-3xl h-fit px-[20px] py-[4px] bg-[#FFA400] text-sm text-gray-800 font-semibold shadow-lg cursor-pointer tracking-[1px] uppercase transition-all duration-150 ease-linear hover:tracking-[2px] hover:bg-[#F77C00] hover:shadow-[0_5px_16px_0px_#F77C00] active:tracking-[3px] active:bg-[#F77C00] active:shadow-[0_0px_0px_0px_#F77C00] active:translate-y-[5px] active:duration-100 `}
                title="Login"
              >
                <Link href="/Login"> Login </Link>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`md:hidden transition-all duration-300 ease-in-out ${
          menuOpen
            ? "  max-h-84 opacity-100"
            : "max-h-0 opacity-0 overflow-hidden"
        } `}
      >
        <div
          className={`px-2 pt-8 pb-3 space-y-1 sm:px-3 bg-[#E5E5E5] mx-3 -mt-4 rounded-b-2xl`}
        >
          {headerLinks.map((h) => (
            <Link
              key={h.href}
              href={h.href}
              onClick={() => setMenuOpen(false)}
              className={` block px-3 py-3 text-base font-medium ${
                pathname === h.href
                  ? `text-[#FFA400] bg-[#dfdcdc] rounded-xl`
                  : ` text-gray-800 hover:text-gray-900 hover:bg-gray-100`
              }`}
              title={`${h.label}`}
            >
              {" "}
              {h.label}
            </Link>
          ))}
        </div>
      </div>
    </nav>
  );

  //   return (
  //     <div>
  //       <div className="md:w-full h-20 flex flex-row md:gap-30 items-center justify-evenly md:justify-between md:px-10 relative">
  //         <div>
  //           <Link href="/">
  //             <img
  //               className="max-w-none"
  //               src="../Images/CSDClubLogo.png"
  //               alt="somgthing"
  //               width={50}F
  //               height={100}
  //             />
  //           </Link>
  //         </div>

  //         <ul className="hidden md:flex gap-6 text-[20px] font-medium font-matrix">
  //           <li>
  //             <Link href="/" className="hover:text-yellow-500 font-bold">
  //               Home
  //             </Link>
  //           </li>
  //           <li>
  //             <Link href="/Blog" className="hover:text-yellow-500 font-bold">
  //               Blog
  //             </Link>
  //           </li>
  //           <li>
  //             <Link href="/Notes" className="hover:text-yellow-500 font-bold">
  //               Notes
  //             </Link>
  //           </li>
  //           <li>
  //             <Link href="/Events" className="hover:text-yellow-500 font-bold">
  //               Events
  //             </Link>
  //           </li>
  //           <li>
  //             <Link href="/Contact" className="hover:text-yellow-500 font-bold">
  //               Contact
  //             </Link>
  //           </li>
  //           <li>
  //             <Link href="/Alumni" className="hover:text-yellow-500 font-bold">
  //               Alumni
  //             </Link>
  //           </li>
  //         </ul>

  //         <button className="bg-yellow-400 hover:bg-yellow-500 text-black font-semibold px-4 py-2 rounded-xl">
  //           <Link href="/Login"> Login </Link>
  //         </button>

  //         <button onClick={() => setMenuOpen(!menuOpen)} className="md:hidden">
  //           <img
  //             className="w-[50px] max-w-none"
  //             src="../Images/HamburgerMenuIcon.webp"
  //             alt="Menu Icon"
  //           />
  //         </button>

  //         {menuOpen && (
  //           <div className="absolute top-20 left-0 w-full bg-white rounded-b-lg pb-[50px] z-[100] md:hidden">
  //             <div className="flex flex-col gap-6 text-[20px] font-medium font-matrix ml-[25px]">
  //               <Link
  //                 href="/"
  //                 className="hover:text-yellow-500 font-bold w-full"
  //                 onClick={() => setMenuOpen(false)}
  //               >
  //                 Home
  //               </Link>
  //               <Link
  //                 href="/Blog"
  //                 className="hover:text-yellow-500 font-bold"
  //                 onClick={() => setMenuOpen(false)}
  //               >
  //                 Blog
  //               </Link>
  //               <Link
  //                 href="/Notes"
  //                 className="hover:text-yellow-500 font-bold"
  //                 onClick={() => setMenuOpen(false)}
  //               >
  //                 Notes
  //               </Link>
  //               <Link
  //                 href="/Events"
  //                 className="hover:text-yellow-500 font-bold"
  //                 onClick={() => setMenuOpen(false)}
  //               >
  //                 Events
  //               </Link>
  //               <Link
  //                 href="/Contact"
  //                 className="hover:text-yellow-500 font-bold"
  //                 onClick={() => setMenuOpen(false)}
  //               >
  //                 Contact
  //               </Link>
  //               <Link
  //                 href="/Alumni"
  //                 className="hover:text-yellow-500 font-bold"
  //                 onClick={() => setMenuOpen(false)}
  //               >
  //                 Alumni
  //               </Link>
  //             </div>
  //           </div>
  //         )}
  //       </div>
  //     </div>
  //   );
}
