// src/lib/components/Footer.svelte
<script lang="ts">
	//TODO update these links, and move them to a icon library
	const socialLinks = [
		{ href: 'https://www.facebook.com/', label: 'Facebook', src: '/Images/FaceBookNew.png' },
		{ href: 'https://www.instagram.com/', label: 'Instagram', src: '/Images/InstagramNew.png' },
		{ href: 'https://x.com/', label: 'Twitter', src: '/Images/TwitterNew.png' },
		{
			href: 'https://github.com/sorrymint/ihcc-csd',
			label: 'GitHub',
			src: '/Images/gitHubLogo.png'
		},
		{ href: 'https://www.linkedin.com/', label: 'LinkedIn', src: '/Images/LinkedInNew.png' }
	];
</script>

<footer class="site-footer">
	<div class="footer-shell">
		<h2 class="font-matrixtype">Interested In Joining?</h2>

		<p class="footer-copy desktop-copy">
			Everyone is welcome to join, <a href="/events">Click Here</a>to view upcoming events
		</p>

		<div class="cta-row">
			<a class="cta-link" href="/contact">Join Now</a>
		</div>

		<div class="footer-grid">
			<a class="shrink-0" href="/" aria-label="Go to home page">
				<img
					src="/Images/Code.svg"
					alt="Computer Software Development Club Logo"
					class="h-20 w-auto md:h-12"
				/>
			</a>

			<div class="social-links">
				{#each socialLinks as link (link.href)}
					<a href={link.href} target="_blank" rel="noreferrer" aria-label={link.label}>
						<img src={link.src} alt={link.label} width="28" height="28" />
					</a>
				{/each}
			</div>
		</div>
	</div>
</footer>

<!-- TODO change to tailwind -->
<style>
	.site-footer {
		margin-top: 4rem;
	}

	.footer-shell {
		background: #e5e5e5;
		padding: 2rem 1rem;
	}

	h2 {
		margin: 0;
		text-align: center;
		font-size: clamp(2rem, 4vw, 2.5rem);
		font-weight: 700;
		color: #701730;
	}

	.footer-copy {
		margin: 1.25rem auto 0;
		max-width: 34rem;
		text-align: center;
		font-size: 0.95rem;
		color: #262626;
	}

	.footer-copy a {
		margin: 0 0.35rem;
		color: #f77c00;
	}

	.cta-row {
		display: flex;
		justify-content: center;
		margin-top: 1.5rem;
	}

	.cta-link {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		padding: 0.8rem 1.5rem;
		border-radius: 999px;
		background: #ffa400;
		color: #262626;
		text-decoration: none;
		font-size: 0.875rem;
		font-weight: 700;
		letter-spacing: 0.08em;
		text-transform: uppercase;
	}

	.footer-grid {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 1.5rem;
		margin-top: 2rem;
	}

	.footer-logo img {
		display: block;
	}

	.quick-links {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 0.75rem;
	}

	.quick-links a {
		color: #000;
		text-decoration: none;
		font-weight: 700;
		text-transform: uppercase;
	}

	.social-links {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 1rem;
		flex-wrap: wrap;
	}

	.social-links img {
		display: block;
	}

	.desktop-copy {
		display: none;
	}

	@media (min-width: 768px) {
		.footer-shell {
			padding: 2rem 1.5rem;
		}

		.footer-grid {
			flex-direction: row;
			justify-content: space-evenly;
		}

		.quick-links {
			flex-direction: row;
			gap: 2rem;
		}

		.desktop-copy {
			display: block;
		}

		.mobile-copy {
			display: none;
		}
	}
</style>

// src/app/Componets/Footer.tsx
import Link from 'next/link'
import Image from "next/image";

export default function Footer() {


    return (
        <div className=" bg-[#DEDEDE]">
            <div className="">
                <h2 className="font-bold flex items-center justify-center text-center text-4xl text-[#701730]">Interested
                    In Joining?</h2>
                <br></br>
                <p className="text-sm flex items-center justify-center text-[#000000]">Everyone is welcome to
                    join,&nbsp;
                    <a className="underline text-sm text-[000000]" href="/Events"> Click Here </a>&nbsp; to view</p>
                <p className="flex items-center justify-center text-sm text-[#000000]"> upcoming events.</p>
            </div>
            <div>
                <br></br>
                <Link href="/Contact" className='flex items-center justify-center'>
                    <p className='rounded-full p-3 pr-6 pl-6 bg-yellow-400 text-sm text-[#000000] hover:bg-yellow-500 shadow-2xl font-bold'>Join
                        Here</p>
                </Link>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
            </div>
            <div className="flex items-center justify-evenly">
                <div>
                    <Link href="/">
                        {/*TODO THIS SHOULD NOT BE AN IMAGE CHANGE TO SVG*/}
                        <Image className="h-25 w-20" src="/Images/CSDClubLogoGray.png" alt="IHCC logo" width={50}
                               height={50}/>
                    </Link>
                </div>
                <div className="flex flex-col md:flex-row md:max-sm:inline-block md:max-sm:pl-15 md:pl-20">
                    <Link href="/Our-Mission"><p className="font-semibold text-[000000] m-3">Our Mission</p></Link>
                    <Link href="/Contact" className='md:pr-9 md:pl-9 font-semibold text-[000000] m-3'>Contact Us</Link>
                    <Link href="/AboutCSD"><p className="font-semibold text-[000000] m-3">About CSD</p></Link>
                </div>
                <div className="flex flex-col md:flex-row">
                    <a href="https://www.facebook.com/" target='_blank'>
                        <Image className="md:mt-1 md:h-7 w-7"
                               src="/Images/FaceBookNew.png"
                               alt="FaceBook"
                               width={50}
                               height={50}
                        >
                        </Image>
                    </a>
                    <a href="https://www.instagram.com/" target='_blank'>
                        <Image
                            className="mt-[5px] md:max-sm:mr-2 md:max-sm:ml-2 md:mr-3 md:ml-3 md:mt-1 h-7 w-7"
                            src="/Images/InstagramNew.png" alt="Instagram"
                            width={50}
                            height={50}
                        >
                        </Image>
                    </a>
                    <a href="https://x.com/" target='_blank'>
                        <Image
                            className="mt-[5px] max-sm:mr-2 md:max-sm:ml-2 md:mt-1 h-7 w-7"
                            src="/Images/TwitterNew.png"
                            alt="Twitter"
                            width={50}
                            height={50}
                        >
                        </Image>
                    </a>
                    <a href="https://github.com/sorrymint/ihcc-csd" target='_blank'>
                        <Image
                            className="mt-[5px] md:max-sm:mr-2 md:max-sm:ml-2 md:mr-3 md:ml-3 md:mt-1 h-7 w-7"
                            src="/Images/gitHubLogo.png" alt="GitHub"
                            width={50}
                            height={50}
                        >
                        </Image>
                    </a>
                    <a href="https://www.linkedin.com/" target='_blank'>
                        <Image className="mt-1 h-7 w-7"
                               src="/Images/LinkedInNew.png"
                               alt="LinkedIn"
                               width={50}
                               height={50}
                        >
                        </Image>
                    </a>
                </div>
            </div>
            <br></br>
        </div>
    );
}
