// src/app/Componets/Header.tsx
"use client";
import Link from "next/link"
import { useState } from "react";
import Image from "next/image";

export default function Header() {

    const [menuOpen, setMenuOpen] = useState(false);

    return (
        <div>
            <div className="md:w-full h-20 flex flex-row md:gap-30 items-center justify-evenly md:justify-between md:px-10 relative">

                <div>
                    <Link href="/">
                        {/*TODO THIS SHOULD NOT BE AN IMAGE CHANGE TO SVG*/}
                        <Image className="max-w-none" src="/Images/CSDClubLogo.png" alt="CSD Club Logo" width={50} height={50} />
                    </Link>
                </div>

                <ul className="hidden md:flex gap-6 text-[20px] font-medium font-matrix">
                    <li>
                        <Link href="/" className="hover:text-yellow-500 font-bold">Home</Link>
                    </li>
                    <li>
                         <Link href="/Blog" className="hover:text-yellow-500 font-bold">Blog</Link>
                    </li>
                    <li>
                         <Link href="/Notes" className="hover:text-yellow-500 font-bold">Notes</Link>
                    </li>
                    <li>
                         <Link href="/Events" className="hover:text-yellow-500 font-bold">Events</Link>
                    </li>
                    <li>
                         <Link href="/Contact" className="hover:text-yellow-500 font-bold">Contact</Link>
                    </li>
                    <li>
                         <Link href="/Alumni" className="hover:text-yellow-500 font-bold">Alumni</Link>
                    </li>
                </ul>

                <button className="bg-yellow-400 hover:bg-yellow-500 text-black font-semibold px-4 py-2 rounded-xl">
                    <Link href="/Login"> Login </Link>
                </button>

                <button onClick ={() => setMenuOpen(!menuOpen)} className="md:hidden">
                    {/*TODO THIS SHOULD NOT BE AN IMAGE CHANGE TO SVG*/}
                    <Image className="w-[50px] max-w-none" src="/Images/HamburgerMenuIcon.webp" width={2} height={2} alt="Menu Icon" />
                </button>

                {menuOpen && (
                    <div className= "absolute top-20 left-0 w-full bg-white rounded-b-lg pb-[50px] z-[100] md:hidden">
                         <div className="flex flex-col gap-6 text-[20px] font-medium font-matrix ml-[25px]">
                                <Link href="/" className="hover:text-yellow-500 font-bold w-full" onClick={() => setMenuOpen(false)}>Home</Link>
                                <Link href="/Blog" className="hover:text-yellow-500 font-bold" onClick={() => setMenuOpen(false)}>Blog</Link>
                                <Link href="/Notes" className="hover:text-yellow-500 font-bold" onClick={() => setMenuOpen(false)}>Notes</Link>
                                <Link href="/Events" className="hover:text-yellow-500 font-bold" onClick={() => setMenuOpen(false)}>Events</Link>
                                <Link href="/Contact" className="hover:text-yellow-500 font-bold" onClick={() => setMenuOpen(false)}>Contact</Link>
                                <Link href="/Alumni" className="hover:text-yellow-500 font-bold" onClick={() => setMenuOpen(false)}>Alumni</Link>
                        </div>
                    </div>
                )
                }
        
          </div>

        </div>
    )
}

// src/lib/components/Header.svelte
<script lang="ts">
	import { page } from '$app/state';

	const links = [
		{ href: '/', label: 'Home' },
		{ href: '/blog', label: 'Blog' },
		{ href: '/notes', label: 'Notes' },
		{ href: '/events', label: 'Events' },
		{ href: '/contact', label: 'Contact' },
		{ href: '/alumni', label: 'Alumni' },
		{ href: '/podcast', label: 'Podcast'},
		{ href: '/aws', label: 'AWS' },
	] as const;

	const isActive = (href: string) =>
		href === '/'
			? page.url.pathname === '/'
			: page.url.pathname === href || page.url.pathname.startsWith(`${href}/`);
</script>

<nav class="fixed top-0 left-0 z-50 w-full px-4 pt-4" aria-label="Main navigation">
	<div class="mx-auto max-w-7xl rounded-2xl bg-neutral-200 px-6 py-4 shadow-lg">
		<div class="flex items-center justify-between gap-6">
			<a class="shrink-0" href="/" aria-label="Go to home page">
				<img
					src="/Images/Code.svg"
					alt="Computer Software Development Club Logo"
					class="h-20 w-auto md:h-12"
				/>
			</a>

			<!-- TODO work on mobile menu -->
			<div class="hidden md:flex flex-1 items-center justify-center gap-x-6">
				{#each links as link}
					<a
						href={link.href}
						class="border-b-2 pb-1 text-base font-semibold transition-colors"
						class:border-[#f77c00]={isActive(link.href)}
						class:text-[#f77c00]={isActive(link.href)}
						class:border-transparent={!isActive(link.href)}
						class:text-zinc-800={!isActive(link.href)}
						class:hover:text-zinc-950={!isActive(link.href)}
					>
						{link.label}
					</a>
				{/each}
			</div>

			<div class="shrink-0">
				<a
					href="/"
					class="rounded-full bg-[#FFA400] px-5 py-2 text-sm font-bold uppercase tracking-wider text-neutral-900 shadow-md transition-colors hover:bg-[#F77C00]"
				>
					Login
				</a>
			</div>
		</div>
	</div>
</nav>
